book_app/urls.py
from django.urls import path
from book_app.views import add_book

urlpatterns = [
    path('add-book/', add_book, name='add_book')
]

book_auth_app/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, logout_then_login
from django.views.generic import CreateView

from book_auth_app.forms import CustomCreationForm


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='auth_app/login.html',
    ), name='login'),
    path('logout/', logout_then_login, name='logout'),

    path('register/', CreateView.as_view(
        template_name='auth_app/register.html',
        form_class=CustomCreationForm,
        success_url='/'
    ), name='register')
]

mybrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from book_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('books/', include(('book_app.urls', 'book_app'), namespace='books')),
    path('auth/', include(('book_auth_app.urls', 'book_auth_app'), namespace='auth')),

    path('', index, name='index'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

book_app/models.py
from django.db import models

from django.conf import settings
from taggit.managers import TaggableManager
from book_auth_app.models import CustomUser

# Create your models here.


class Books(models.Model):
    title = models.CharField(max_length=300)

    # Linking
    author = models.ForeignKey('Authors', on_delete=models.PROTECT)
    rating = models.ForeignKey('Rates', on_delete=models.PROTECT)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    tags = TaggableManager()

    # Utils
    read = models.BooleanField()

    def mark_read(self, commit=True):
        self.read = True
        if commit:
            self.save()

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Authors(models.Model):
    full_name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.full_name)


class Categories(models.Model):
    category = models.CharField(max_length=30)

    def __str__(self):
        return str(self.category)


class Rates(models.Model):
    BAD = ('B', 'bad')
    GOOD = ('G', 'good')
    EXCELLENT = ('E', 'excellent')
    __all = dict([BAD, GOOD, EXCELLENT])

    rate = models.CharField(max_length=2, choices=__all.items())

    def __str__(self):
        return str(self.__all[self.rate])

book_auth_app/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    our_note = models.CharField(max_length=140, blank=True)

book_app/forms.py
from django import forms
from book_app.models import Books, Authors


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Authors
        fields = [
            'full_name',
        ]


class BooksForm(forms.ModelForm):
    # category = forms.fields.CharField(required=False)
    class Meta:
        model = Books
        exclude = [
            'author',
            'user',
        ]

    def save(self, commit=True, author=None, user=None):
        if author is None:
            raise ValueError('authors name was not set')
        if user is None:
            raise ValueError('user was not set')

        inst = super().save(commit=False)
        inst.author = author
        inst.user = user

        if commit:
            inst.save()

        return inst

book_auth_app/forms.py
from django.contrib.auth.forms import UserCreationForm

from book_auth_app.models import CustomUser


class CustomCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            'username',
        ]

book_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.db import transaction

from book_app.models import Books
from book_app.forms import BooksForm, AuthorForm

# Create your views here.


def index(request):
    if request.method == 'GET':
        user = request.user
        if str(user) == 'AnonymousUser':
            return render(request, 'book_app/index.html')
        else:
            # print(user, filtered_books)
            filtered_books = Books.objects.filter(user__exact=user)
            books = Books.objects.all()
            return render(request, 'book_app/index.html', {'books': filtered_books})

    return HttpResponse(status=405)


def add_book(request):
    if request.method == 'GET':
        c = {
            'book_form': BooksForm(),
            'author_form': AuthorForm(),
        }
        return render(request, 'book_app/add-book.html', c)

    elif request.method == 'POST':
        book_form = BooksForm(request.POST)
        author_form = AuthorForm(request.POST)
        user = request.user

        if book_form.is_valid() and author_form.is_valid():
            with transaction.atomic():
                author = author_form.save()
                book_form.save(user=user, author=author)
                book_form.save_m2m()

            return redirect(reverse('index'))

book_auth_app/views.py
from django.shortcuts import render

# Create your views here.

book_app/templates/book_app/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <p>{{ user.username }}</p>
    <p>{{ perms }}</p>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

book_app/templates/book_app/add-book.html
{% extends 'book_app/_base.html' %}

{% block content %}

    <form action="{% url 'books:add_book' %}" method="POST">
    {% csrf_token %}

    <h2>book</h2>

    {{ author_form.as_p }}
    {{ book_form.as_p }}

    {% if user.is_anonymous %}

        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            add</button>

<!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">You're logged out</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <p>You need to log in first</p>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <a href="http://127.0.0.1:8000/auth/login/" type="button" class="btn btn-primary">
                            Go to log in page</a>
                        </form>
                    </div>

                </div>
            </div>
        </div>

    {% else %}

        <input type="submit" value="add" />

    {% endif %}
    </form>

    <form action="http://127.0.0.1:8000/">
        <button>Back to main</button>
    </form>

{% endblock %}

book_app/templates/book_app/index.html
{% extends 'book_app/_base.html' %}

{% block content %}
    {% if user.is_anonymous %}
        <h2>Your books</h2>
        <p>Want to see your own books? You need to login first</p>

        <form action="http://127.0.0.1:8000/auth/login">
            <button>log in</button>
        </form>
    {% else %}
    <h2>Your books</h2>

    <ul>
    {% for book in books %}
        {% if book.read %}

            <li>
                <p>{{ book.id }}</p>
                <p>{{ book.author }}</p>
                <p>{{ book.title }}</p>
                <p>
                    {% for tag in book.tags.all %}
                    {{ tag }},
                    {% endfor %}
                </p>
                <p>{{ book.rating }}</p>
                <p>{{ book.read }}</p>
            </li>

        {% endif %}
    {% endfor %}

    <hr />

    {% for book in books %}
        {% if not book.read %}

            <li>
                <p>{{ book.id }}</p>
                <p>{{ book.author }}</p>
                <p>{{ book.title }}</p>
                <p>
                    {% for tag in book.tags.all %}
                    {{ tag }},
                    {% endfor %}
                </p>
                <p>{{ book.rating }}</p>
                <p>{{ book.read }}</p>
            </li>

        {% endif %}
    {% endfor %}
    </ul>
    {% endif %}

    <form action="http://127.0.0.1:8000/books/add-book/">
        <button>Добавить</button>
    </form>

{% endblock %}

book_auth_app/templates/auth_app/login.html
{% extends 'book_app/_base.html' %}

{% block content %}

    <h2>Logging in</h2>

    <form action="{% url 'auth:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

book_auth_app/templates/auth_app/register.html
{% extends 'book_app/_base.html' %}

{% block content %}

    <h2>Register</h2>

    <form action="{% url 'auth:register' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

mybrary_app/templates/mybrary_app/index.html
{% extends 'mybrary_app/_base.html' %}

{% block content %}

    <h2>Your books</h2>

    <ul>
    {% for book in books %}
        {% if book.read %}

            <li>
                <p>{{ book.id }}</p>
                <p>{{ book.author }}</p>
                <p>{{ book.title }}</p>
                <p>{{ book.category }}</p>
                <p>{{ book.rating }}</p>
                <p>{{ book.read }}</p>
            </li>

        {% endif %}
    {% endfor %}

    <hr />

    {% for book in books %}
        {% if not book.read %}

            <li>
                <p>{{ book.id }}</p>
                <p>{{ book.author }}</p>
                <p>{{ book.title }}</p>
                <p>{{ book.category }}</p>
                <p>{{ book.rating }}</p>
                <p>{{ book.read }}</p>
            </li>

        {% endif %}
    {% endfor %}
    </ul>

    <form action="http://127.0.0.1:8000/books/add-book/">
        <button>Add new book</button>
    </form>

{% endblock %}